version: '3.9'

services:
  backend:
    build:
      context: ./game-backend
    network_mode: "host" # Ensure the backend can reach the host's network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./game-frontend
    network_mode: "host" # Ensure the frontend can reach the host's network
    ports:
      - "3000:3000"

  leaderboard:
    build:
      context: ./leaderboard
    network_mode: "host" # Ensure the leaderboard can reach the host's network
    ports:
      - "8081:8081"
